services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/landbot
    command: >
      bash -c "python -m src.shared.infrastructure.persistence.wait_for_db && 
               uvicorn src.shared.infrastructure.api.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=landbot
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  rabbitmq_data:
