"""team_notifier_config

Revision ID: 81a789143d0b
Revises: d671e4f61317
Create Date: 2025-04-06 18:05:46.477244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a789143d0b'
down_revision: Union[str, None] = 'd671e4f61317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_notifier_config',
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_notifier_config')
    # ### end Alembic commands ###
